# Generated by Django 4.1.3 on 2022-11-16 08:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ani_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='visitors',
            field=models.ManyToManyField(related_name='%(model_name)s_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 8, 32, 27, 949806, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 8, 32, 27, 951826, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='series',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 8, 32, 27, 953826, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
