# Generated by Django 4.1.2 on 2022-10-26 07:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ani_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='parent_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ani_app.serials', verbose_name='коментарии'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 7, 33, 36, 349466, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='comment')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 7, 33, 36, 350452, tzinfo=datetime.timezone.utc), verbose_name='date_published')),
                ('is_published', models.BooleanField(default=False, verbose_name='is_published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ani_app.serials', verbose_name='serial')),
            ],
        ),
    ]
