# Generated by Django 4.1.3 on 2022-11-16 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0002_serials_visitors_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='visits'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 3, 14, 706184, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 3, 14, 709184, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='series',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 3, 14, 711182, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
