# Generated by Django 4.1.2 on 2022-11-04 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0003_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 12, 1, 28, 728946, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 12, 1, 28, 730948, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='series',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 12, 1, 28, 731947, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
