# Generated by Django 4.1.3 on 2022-11-16 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0003_serials_visits_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serials',
            name='visits',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 19, 18, 43179, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 19, 18, 46200, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='series',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 19, 18, 47199, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
