# Generated by Django 4.1.2 on 2022-10-26 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0005_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serials',
            name='parent_com',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 12, 10, 14, 724251, tzinfo=datetime.timezone.utc), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 12, 10, 14, 723251, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
