# Generated by Django 4.1.2 on 2022-10-26 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0006_remove_serials_parent_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 13, 14, 34, 293888, tzinfo=datetime.timezone.utc), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 13, 14, 34, 292910, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
