# Generated by Django 4.1.2 on 2022-10-28 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0010_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='serial',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 14, 43, 42, 392285, tzinfo=datetime.timezone.utc), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 14, 43, 42, 392285, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='pk_comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ani_app.comments', verbose_name='pk_comm'),
        ),
    ]
