# Generated by Django 4.1.2 on 2022-10-28 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani_app', '0012_comments_serial_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('date_published',), 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 19, 33, 17, 473680, tzinfo=datetime.timezone.utc), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 19, 33, 17, 474679, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='anime_comments',
        ),
    ]
