# Generated by Django 4.1.3 on 2022-11-15 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ani_app', '0003_alter_comments_date_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='subtitle')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 6, 22, 727050, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('image', models.ImageField(upload_to='blog/')),
                ('is_published', models.BooleanField(default=False, null=True, verbose_name='is_published')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ManyToManyField(blank=True, null=True, to='ani_app.categories', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'blog_post',
                'ordering': ('date_published', 'is_published'),
            },
        ),
    ]
