# Generated by Django 4.1.3 on 2022-11-16 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 8, 32, 27, 955827, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
    ]
