# Generated by Django 4.1.3 on 2022-11-16 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 19, 18, 49200, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
    ]
