# Generated by Django 4.1.3 on 2022-11-17 11:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_blog_date_published_alter_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visitors',
            field=models.ManyToManyField(related_name='%(model_name)s_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 11, 17, 4, 253134, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
    ]
