# Generated by Django 4.1.3 on 2022-11-17 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_visitors_alter_blog_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 11, 19, 29, 203701, tzinfo=datetime.timezone.utc), null=True, verbose_name='date_published'),
        ),
    ]
